### *Parsa Nikpour*

### *Email: parsanikpour@ut.ac.ir*

# **Import**

In [3]:
import itertools
import numpy as np
from numpy import linalg as LA
from scipy.stats import gmean
import scipy.optimize as optimize

In [4]:
"""
import pandas as pd
#dataset = pd.read_excel("dataset.xlsx")    # اگر دیتای شما در فایل اکسل است
#dataset = pd.read_csv("dataset.csv")       # اگر دیتای شما در فایل csv است
dataset = np.array(dataset)
"""

'\nimport pandas as pd\n#dataset = pd.read_excel("dataset.xlsx")    # اگر دیتای شما در فایل اکسل است\n#dataset = pd.read_csv("dataset.csv")       # اگر دیتای شما در فایل csv است\ndataset = np.array(dataset)\n'

#**Numpy**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#0 Dimensional Array
import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
# 1 Dimensional array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
# 2 Dimensional array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 Dimensional Array
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[2 4]
[1 3 5 7]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Flattening
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

print("\n")

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


print("\n")

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3


[1 2 3]
[4 5 6]


1
2
3
4
5
6


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr2[0,1] =7

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


#**Likert and Normalization**

In [8]:
# مقیاس لیکرت
def Likert(dataset, criterion):
  for i in range(dataset.shape[0]):
          for j in range(dataset.shape[1]):
              if dataset[i,j] == "Very Low":
                if criterion[j] == 'max':
                  dataset[i,j] = 1
                else:
                  dataset[i,j] = 9

              if dataset[i,j] == "Low":
                if criterion[j] == 'max':
                  dataset[i,j] = 3
                else:
                  dataset[i,j] = 7

              if dataset[i,j] == "Neutral":
                  dataset[i,j] = 5

              if dataset[i,j] == "Much":
                if criterion[j] == 'max':
                  dataset[i,j] = 7
                else:
                  dataset[i,j] = 3

              if dataset[i,j] == "Very Much":
                if criterion[j] == 'max':
                  dataset[i,j] = 9
                else:
                  dataset[i,j] = 1
  return(np.array(dataset,dtype='f'))

In [9]:
# مقایس لیکرت ماتریس مقایسات زوجی
def Likert_PCM(dataset):
  for i in range(dataset.shape[0]):
          for j in range(dataset.shape[1]):
              if dataset[i,j] == "Equally Preferred":
                  dataset[i,j] = 1

              if dataset[i,j] == "Moderately Preferred":
                  dataset[i,j] = 3

              if dataset[i,j] == "Strongly Preferred":
                  dataset[i,j] = 5

              if dataset[i,j] == "Very Strongly Preferred":
                  dataset[i,j] = 7

              if dataset[i,j] == "Extremely Preferred":
                  dataset[i,j] = 9
  for i in range(dataset.shape[0]):
          for j in range(dataset.shape[1]):
              if float(dataset[i,j]) == 0:
                  dataset[i,j] = 1/float(dataset[j,i])
  return(np.array(dataset,dtype='f'))

dataset = np.array([[1 , "Extremely Preferred" , "Very Strongly Preferred"],
                    [0 ,            1          ,  "Equally Preferred"     ],
                    [0 ,            0          ,           1              ]])
Likert_PCM(dataset)

array([[1.        , 9.        , 7.        ],
       [0.11111111, 1.        , 1.        ],
       [0.14285715, 1.        , 1.        ]], dtype=float32)

In [10]:
# بی مقیاس سازی خطی - نرمالیزه کردن خطی
def NormMinMax(dataset,criterion):
      dataset = Likert(dataset, criterion)

      for j in range(dataset.shape[1]):
          if criterion[j] == 'max':
              dataset[:,j] = dataset[:,j] /np.max(dataset[:,j])

          else:
              dataset[:,j] = np.min(dataset[:,j])/dataset[:,j]

      return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral" ]]))
criterion = ['max','max','max','min','max','max']
NormMinMax(dataset, criterion)

array([[0.8       , 0.5555556 , 0.95238096, 0.8181818 , 0.71428573,
        1.        ],
       [1.        , 1.        , 0.85714287, 0.6923077 , 0.42857143,
        0.5555556 ],
       [0.71999997, 0.7407407 , 1.        , 1.        , 1.        ,
        0.7777778 ],
       [0.88      , 0.6666667 , 0.95238096, 0.9       , 0.71428573,
        0.5555556 ]], dtype=float32)

In [11]:
# نرمالیزه کردن ساده
def Normalization(dataset,criterion):
      dataset = Likert(dataset, criterion)
      dataset = np.array(dataset, dtype='f')
      dataset = dataset/np.sum(dataset,axis=0)

      return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral" ]]))
criterion = ['max','max','max','min','max','max']
Normalization(dataset, criterion)

array([[0.23529412, 0.1875    , 0.25316456, 0.25581396, 0.25      ,
        0.34615386],
       [0.29411766, 0.3375    , 0.2278481 , 0.30232558, 0.15      ,
        0.1923077 ],
       [0.2117647 , 0.25      , 0.2658228 , 0.20930232, 0.35      ,
        0.26923078],
       [0.25882354, 0.225     , 0.25316456, 0.23255815, 0.25      ,
        0.1923077 ]], dtype=float32)

In [12]:
# روش برداری
def Euclidean(dataset,criterion):
      dataset = Likert(dataset, criterion)
      dataset = np.array(dataset, dtype='f')
      dataset = dataset/np.sqrt(np.sum(np.square(dataset),axis=0))

      return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral" ]]))
criterion = ['max','max','max','min','max','max']
Euclidean(dataset, criterion)

array([[0.46714184, 0.36618057, 0.5055601 , 0.5068533 , 0.48112524,
        0.6708204 ],
       [0.5839273 , 0.659125  , 0.45500413, 0.5990084 , 0.28867516,
        0.372678  ],
       [0.42042765, 0.48824075, 0.53083813, 0.41469812, 0.67357534,
        0.5217492 ],
       [0.51385605, 0.43941668, 0.5055601 , 0.4607757 , 0.48112524,
        0.372678  ]], dtype=float32)

In [13]:
# روش نرمالیزه کردن فازی
def FuzzyNorm(dataset,criterion):
      dataset = Likert(dataset, criterion)
      dataset = np.array(dataset, dtype='f')

      for j in range(dataset.shape[1]):
          if criterion[j] == 'max':
              dataset[:,j] = (dataset[:,j] - np.min(dataset[:,j]))/(np.max(dataset[:,j]) - np.min(dataset[:,j]))

          else:
              dataset[:,j] = (np.max(dataset[:,j]) - dataset[:,j])/(np.max(dataset[:,j]) - np.min(dataset[:,j]))

      return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral" ]]))
criterion = ['max','max','max','min','max','max']
FuzzyNorm(dataset, criterion)

array([[0.28571433, 0.        , 0.6666667 , 0.5       , 0.5       ,
        1.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.41666666, 1.        , 1.        , 1.        ,
        0.5       ],
       [0.57142866, 0.25      , 0.6666667 , 0.75      , 0.5       ,
        0.        ]], dtype=float32)

#**Non-Compensatory**

In [ ]:
# روش تسلط

import itertools
import numpy as np

def Dominance(dataset, criterion):
      dataset = Likert(dataset, criterion)

      for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]

      for i in range (dataset.shape[0]):

          Dominance = np.greater_equal(dataset[i,:],dataset)

          for x in range(Dominance.shape[0]):
              if x!=i:
                if Dominance[x,:].all() == True:
                  print("Option", i+1 ,"is dominant over ", x+1)
                  dataset =np.delete(dataset,x,0)
      np.set_printoptions(suppress = True)
      return(dataset)


dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Very Much"   ]]))
criterion = ['max','max','max','min','max','max']
Dominance(dataset, criterion)


Option 4 is dominant over  1


array([[    2.5,  2700. , 18000. ,    -6.5,     3. ,     5. ],
       [    1.8,  2000. , 21000. ,    -4.5,     7. ,     7. ],
       [    2.2,  1800. , 20000. ,    -5. ,     5. ,     9. ]],
      dtype=float32)

In [ ]:
# روش حداکثر حداقل‌ها
def Maximin (dataset, criterion):
    dataset = NormMinMax(dataset,criterion)
    Rank = np.max(np.min(dataset, axis=1))

    for i in range(dataset.shape[0]):
      if np.min(dataset[i,:]) == Rank:
          print("Option" , i+1 ,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
criterion = ['max','max','max','min','max','max']
Maximin(dataset, criterion)

Option 3 is selected


In [ ]:
# روش حداکثر حداکثرها
def Maximax (dataset, criterion):

    dataset = NormMinMax(dataset,criterion)
    Rank = np.max(np.max(dataset, axis=1))

    for i in range(dataset.shape[0]):
      if np.max(dataset[i,:]) == Rank:
          print("Option" , i+1 ,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
criterion = ['max','max','max','min','max','max']
Maximax(dataset, criterion)

Option 1 is selected
Option 2 is selected
Option 3 is selected


In [ ]:
# روش هروکس
def Hurwicz(dataset , alpha , criterion):
    dataset = NormMinMax(dataset,criterion)
    H = alpha*np.min(dataset, axis=1) + (1-alpha)*np.max(dataset, axis=1)
    Rank = np.max(H)

    for i in range(H.shape[0]):
        if H[i] == Rank:
          print("Option",i+1,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
criterion = ['max','max','max','min','max','max']
Hurwicz(dataset , 0.05 , criterion)

Option 3 is selected


In [ ]:
# روش ارضای جامع
def Conjunctive(dataset , criterion, Threshold):
    dataset = Likert(dataset, criterion)

    for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]
            T[j] = - T[j]

    for i in range(dataset.shape[0]):
        if np.greater_equal(dataset[i,:], Threshold).all() == True:
          print("Option",i+1,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
T = np.array(([1.8 , 1500 , 15000 , 6 , 5 , 6]),dtype='f')
criterion = ['max','max','max','min','max','max']
Conjunctive(dataset , criterion , T)

Option 1 is selected
Option 3 is selected


In [ ]:
# روش ارضای تکی
def Disjunctive(dataset , criterion, Threshold):
    dataset = Likert(dataset, criterion)

    for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]
            T[j] = - T[j]

    for i in range(dataset.shape[0]):
        if np.greater_equal(dataset[i,:], Threshold).any() == True:
          print("Option",i+1,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.2 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
T = np.array(([2.3 ,  2000 , 22000 , 4.5 , 6 , 8]),dtype='f')
criterion = ['max','max','max','min','max','max']
Disjunctive(dataset , criterion , T)

Option 1 is selected
Option 2 is selected
Option 3 is selected


In [ ]:
# روش لغت نامه‌ای
def Lexicographic(dataset , criterion, Prio):
    dataset = Likert(dataset, criterion)
    data2 = np.copy(dataset)
    for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]

    for j in range(Prio.shape[0]):
        Best = np.max(dataset[:,Prio[j]-1])
        dataset = np.delete(dataset, np.where((dataset[:,Prio[j]-1] !=Best))[0], axis=0)
        if dataset.shape[0] == 1:
            for j in range (dataset.shape[1]):
                if criterion[j] == 'min':
                  dataset[:,j] = -dataset[:,j]
            print("Option",np.where((data2==dataset).all(-1))[0][0]+1, "is selected")
            return(dataset)




dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.2 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Very Much"   ]]))
Prio = np.array([1,3,2,4,5,6])
criterion = ['max','max','max','min','max','max']
Lexicographic(dataset , criterion , Prio)

Option 4 is selected


array([[2.2e+00, 1.8e+03, 2.0e+04, 5.0e+00, 5.0e+00, 9.0e+00]],
      dtype=float32)

In [ ]:
# روش نیمه لغت‌ نامه‌ای
def SemiLexicographic(dataset , criterion, Prio, Tolerance):
    dataset = Likert(dataset, criterion)
    data2 = np.copy(dataset)
    for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]

    for j in range(Prio.shape[0]):
        Best = np.max(dataset[:,Prio[j]-1])
        dataset = np.delete(dataset, np.where((dataset[:,Prio[j]-1] <Best*(1-Tolerance)))[0], axis=0)

        if dataset.shape[0] == 1:
            for j in range (dataset.shape[1]):
                if criterion[j] == 'min':
                  dataset[:,j] = -dataset[:,j]
            print("Option",np.where((data2==dataset).all(-1))[0][0]+1, "is selected")
            return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.2 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Very Much"   ]]))
Prio = np.array([1,3,2,4,5,6])
Tolerance = 0.1
criterion = ['max','max','max','min','max','max']
SemiLexicographic(dataset , criterion , Prio, Tolerance)

Option 2 is selected


array([[2.2e+00, 2.7e+03, 1.8e+04, 6.5e+00, 3.0e+00, 5.0e+00]],
      dtype=float32)

In [ ]:
# روش جایگشت
def Permutation(dataset , criterion, weight):
      dataset = Likert(dataset, criterion)

      for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]

      # Computing pairwise weights
      H = np.empty((dataset.shape[0] , dataset.shape[0]))
      for i in range(dataset.shape[0]):
        for j in range(dataset.shape[0]):
          H[i,j] = np.sum(weight[np.where(np.greater_equal(dataset[i,:], dataset[j,:]))[0]])

      #Permutations of Options
      s = np.arange(weight.shape[0])
      comb = itertools.permutations(s, weight.shape[0])
      Per = np.array(list(comb))

      #Accordant Set
      #Dissenting Set

      Acc= np.empty((Per.shape[0], 1))
      Diss= np.empty((Per.shape[0], 1))

      for k in range(Per.shape[0]):
        s=0
        x=0
        for i in range(Per.shape[1]):
          for j in range(i+1, Per.shape[1]):
            a = Per[k,i]
            b = Per[k,j]
            s+= H[a,b]
            x+= H[b,a]
          Acc[k,:] = s
          Diss[k,:] = x

      Permutation = Acc - Diss
      print(Per[np.argmax(Permutation)])


dataset = np.array(([[2    ,  15  ,  20],
                     [2.2  ,  27  ,  18],
                     [1.8  ,  20  ,  20]]))
criterion = np.array(['max', 'min' , 'max'])
weight = np.array([0.2 , 0.5 , 0.3])

Permutation(dataset , criterion, weight)

[0 2 1]


#**Compensatory**

In [ ]:
# آنتروپی

def entropy_method(dataset, criterion):
    # Decision Matrix
    dataset = Normalization(dataset, criterion)
    ln_dataset = np.log(dataset)

    #Entropy
    E = np.zeros((dataset.shape))
    K = 1/np.log(dataset.shape[0])
    E = -K*np.sum(dataset*ln_dataset, axis=0)

    #d
    d = 1 - E

    #Weight
    w = d / (np.sum(d))

    print("Entropy:", E)
    print("Matrix d:", d)
    print("Weights:", w)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  5 , 9 ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  3 , 5 ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  7 , 7 ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  5 , 5 ]]))
criterion = ['max','max','max','min','max','max']
entropy_method(dataset, criterion)

Entropy: [0.9946889  0.9829482  0.99888754 0.99327105 0.97032267 0.97714126]
Matrix d: [0.00531107 0.01705182 0.00111246 0.00672895 0.02967733 0.02285874]
Weights: [0.06418961 0.20608823 0.0134452  0.08132605 0.3586802  0.2762707 ]


In [ ]:
# مجموع وزنی ساده

def SAW(dataset, weights, criterion):
    dataset = NormMinMax(dataset, criterion)
    weighted = np.sum(dataset*weights, axis = 1)
    sorted = np.sort(weighted)
    print("Weighted:", weighted)
    for i in range (sorted.shape[0]):
      print("rank", i+1 ,"is option",np.where(weighted==sorted[-(i+1)])[0][0]+1)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  5 , 9 ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  3 , 5 ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  7 , 7 ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  5 , 5 ]]))
w = np.array([0.2,   0.1,   0.1,   0.1,  0.2,  0.3])
criterion = ['max','max','max','min','max','max']
SAW(dataset, w, criterion)

Weighted: [0.83546898 0.70732602 0.8514074  0.73742858]
rank 1 is option 3
rank 2 is option 1
rank 3 is option 4
rank 4 is option 2


In [ ]:
# روش وزنی ترکیبی

def WASPAS(dataset, weights, Lambda, criterion):
    dataset = NormMinMax(dataset, criterion)
    weighted_sum = np.sum(dataset*weights, axis = 1)
    weighted_product = np.prod(dataset**weights, axis = 1)
    was = Lambda*weighted_sum + (1-Lambda)*weighted_product
    sorted = np.sort(was)
    print("Weighted:", was)
    for i in range (sorted.shape[0]):
      print("rank", i+1 ,"is option",np.where(was==sorted[-(i+1)])[0][0]+1)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  5 , 9 ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  3 , 5 ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  9 , 3 ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  5 , 5 ]]))
w = np.array([0.2,   0.1,   0.1,   0.1,  0.2,  0.3])
criterion = ['max','max','max','min','max','max']
WASPAS(dataset, w, 0.8 ,criterion)

Weighted: [0.79937676 0.67837223 0.70517465 0.70194596]
rank 1 is option 1
rank 2 is option 3
rank 3 is option 4
rank 4 is option 2


In [19]:
# ماتریس مقایسات زوجی

def PCM(dataset, IIR, In_method, Weight_method):
      dataset = Likert_PCM(dataset)
      eigenvalues, eigenvectors = LA.eig(dataset)
      Lambda = np.max(abs(eigenvalues.real))
      II = (Lambda-dataset.shape[0])/(dataset.shape[0]-1)
      IR = II/(IIR[dataset.shape[0]-1])

      if IR>0.1:
          print("Inconsistent PCM")
          # روش لگاریتم کمترین مربعات
          if In_method == "LLSM":
              W = np.prod(dataset, axis=1)**(1/dataset.shape[0])/np.sum(np.prod(dataset, axis=1)**(1/dataset.shape[0]))
              print("Weights with LLSM method:", W)


          # روش مقدار ویژه
          if In_method == "EVM":
              b = np.zeros(dataset.shape[0])
              def f(w):
                  y = np.dot((dataset - Lambda*np.identity(dataset.shape[0])),w) - b
                  return np.dot(y,y)

              cons = ({'type': 'eq', 'fun': lambda w: w.sum() - 1})
              res = optimize.minimize(f, np.zeros(dataset.shape[0]), method='SLSQP', constraints=cons,
                                      options={'disp': False})
              W = res['x']
              print("Weights with EVM method:", W)


          # روش کمترین مربعات
          if In_method == "LSM":
              def f(w):
                  y =0
                  for i in range (dataset.shape[0]):
                      for j in range(dataset.shape[1]):
                          y += (dataset[i,j]*w[j]-w[i])**2
                  return y

              cons = ({'type': 'eq', 'fun': lambda w: w.sum() - 1})
              res = optimize.minimize(f, np.zeros(dataset.shape[0]), method='SLSQP', constraints=cons,
                                      options={'disp': False})
              W = res['x']
              print("Weights with LSM method:", W)


      else:
          # جمع سطری
          if Weight_method == "Row":
              dataset = np.sum(dataset, axis = 1)
              dataset = dataset/np.sum(dataset)
              print("Weights with summation of rows method:", dataset)
              return
          # جمع ستونی
          elif Weight_method == "Column":
              dataset = np.sum(dataset, axis = 0)
              dataset = 1/dataset
              dataset = dataset/np.sum(dataset)
              print("Weights summation of columns method:", dataset)
              return

          # میانگین حسابی
          elif Weight_method == "Arithmetic Mean":
              dataset = dataset/np.sum(dataset, axis =0)
              dataset = np.mean(dataset, axis=1)
              print("Weights with Arithmetic mean method:", dataset)
              return

          # میانگین هندسی
          elif Weight_method == "Geometric Mean":
              dataset = gmean(dataset, axis = 1)
              dataset = dataset/np.sum(dataset)
              print("Weights with Geometric mean method:", dataset)
              return

dataset = np.array(([[ 1   ,  5   ,  6   ,  7],
                     [1/5  ,  1   ,  4   ,  6],
                     [1/6  ,  1/4 ,  1   ,  4],
                     [1/7  ,  1/6 ,  1/4 ,  1]]))
IIR = np.array([0 , 0 , 0.58 ,  0.9, 1.12, 1.24, 1.32, 1.41, 1.45, 1.51])
Weight_method = "Row"
In_method = "EVM"
PCM(dataset, IIR, In_method, Weight_method)


Inconsistent PCM
Weights with EVM method: [0.61867427 0.23531693 0.10093078 0.04507801]
