### *Parsa Nikpour*

### *Email: parsanikpour@ut.ac.ir*

# **Import**

In [ ]:
import itertools
import numpy as np
from numpy import linalg as LA
from scipy.stats import gmean
import scipy.optimize as optimize
from scipy.optimize import minimize, Bounds, NonlinearConstraint, LinearConstraint

In [ ]:
"""
import pandas as pd
#dataset = pd.read_excel("dataset.xlsx")    # اگر دیتای شما در فایل اکسل است
#dataset = pd.read_csv("dataset.csv")       # اگر دیتای شما در فایل csv است
dataset = np.array(dataset)
"""

'\nimport pandas as pd\n#dataset = pd.read_excel("dataset.xlsx")    # اگر دیتای شما در فایل اکسل است\n#dataset = pd.read_csv("dataset.csv")       # اگر دیتای شما در فایل csv است\ndataset = np.array(dataset)\n'

#**Numpy**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#0 Dimensional Array
import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
# 1 Dimensional array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
# 2 Dimensional array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 Dimensional Array
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[2 4]
[1 3 5 7]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Flattening
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

print("\n")

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


print("\n")

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3


[1 2 3]
[4 5 6]


1
2
3
4
5
6


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr2[0,1] =7

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


#**Likert and Normalization**

In [ ]:
# مقیاس لیکرت
def Likert(dataset, criterion):
  for i in range(dataset.shape[0]):
          for j in range(dataset.shape[1]):
              if dataset[i,j] == "Very Low":
                if criterion[j] == 'max':
                  dataset[i,j] = 1
                else:
                  dataset[i,j] = 9

              if dataset[i,j] == "Low":
                if criterion[j] == 'max':
                  dataset[i,j] = 3
                else:
                  dataset[i,j] = 7

              if dataset[i,j] == "Neutral":
                  dataset[i,j] = 5

              if dataset[i,j] == "Much":
                if criterion[j] == 'max':
                  dataset[i,j] = 7
                else:
                  dataset[i,j] = 3

              if dataset[i,j] == "Very Much":
                if criterion[j] == 'max':
                  dataset[i,j] = 9
                else:
                  dataset[i,j] = 1
  return(np.array(dataset,dtype='f'))

In [ ]:
# مقایس لیکرت ماتریس مقایسات زوجی
def Likert_PCM(dataset):
  if dataset.ndim>1:
      for i in range(dataset.shape[0]):
              for j in range(dataset.shape[1]):
                  if dataset[i,j] == "Equally Preferred":
                      dataset[i,j] = 1

                  elif dataset[i,j] == "Moderately Preferred":
                      dataset[i,j] = 3

                  elif dataset[i,j] == "Strongly Preferred":
                      dataset[i,j] = 5

                  elif dataset[i,j] == "Very Strongly Preferred":
                      dataset[i,j] = 7

                  elif dataset[i,j] == "Extremely Preferred":
                      dataset[i,j] = 9
      for i in range(dataset.shape[0]):
              for j in range(dataset.shape[1]):
                  if float(dataset[i,j]) == 0:
                      dataset[i,j] = 1/float(dataset[j,i])
  else:
      for i in range(dataset.shape[0]):
                  if dataset[i] == "Equally Preferred":
                      dataset[i] = 1

                  elif dataset[i] == "Moderately Preferred":
                      dataset[i] = 3

                  elif dataset[i] == "Strongly Preferred":
                      dataset[i] = 5

                  elif dataset[i] == "Very Strongly Preferred":
                      dataset[i] = 7

                  elif dataset[i] == "Extremely Preferred":
                      dataset[i] = 9

  return(np.array(dataset,dtype='f'))

dataset = np.array([[1 , "Extremely Preferred" , "Very Strongly Preferred"],
                    [0 ,            1          ,  "Equally Preferred"     ],
                    [0 ,            0          ,           1              ]])
Likert_PCM(dataset)

array([[1.        , 9.        , 7.        ],
       [0.11111111, 1.        , 1.        ],
       [0.14285715, 1.        , 1.        ]], dtype=float32)

In [ ]:
# بی مقیاس سازی خطی - نرمالیزه کردن خطی
def NormMinMax(dataset,criterion):
      dataset = Likert(dataset, criterion)

      for j in range(dataset.shape[1]):
          if criterion[j] == 'max':
              dataset[:,j] = dataset[:,j] /np.max(dataset[:,j])

          else:
              dataset[:,j] = np.min(dataset[:,j])/dataset[:,j]

      return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral" ]]))
criterion = ['max','max','max','min','max','max']
NormMinMax(dataset, criterion)

array([[0.8       , 0.5555556 , 0.95238096, 0.8181818 , 0.71428573,
        1.        ],
       [1.        , 1.        , 0.85714287, 0.6923077 , 0.42857143,
        0.5555556 ],
       [0.71999997, 0.7407407 , 1.        , 1.        , 1.        ,
        0.7777778 ],
       [0.88      , 0.6666667 , 0.95238096, 0.9       , 0.71428573,
        0.5555556 ]], dtype=float32)

In [ ]:
# نرمالیزه کردن ساده
def Normalization(dataset,criterion):
      dataset = Likert(dataset, criterion)
      dataset = np.array(dataset, dtype='f')
      dataset = dataset/np.sum(dataset,axis=0)

      return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral" ]]))
criterion = ['max','max','max','min','max','max']
Normalization(dataset, criterion)

array([[0.23529412, 0.1875    , 0.25316456, 0.25581396, 0.25      ,
        0.34615386],
       [0.29411766, 0.3375    , 0.2278481 , 0.30232558, 0.15      ,
        0.1923077 ],
       [0.2117647 , 0.25      , 0.2658228 , 0.20930232, 0.35      ,
        0.26923078],
       [0.25882354, 0.225     , 0.25316456, 0.23255815, 0.25      ,
        0.1923077 ]], dtype=float32)

In [ ]:
# روش برداری
def Euclidean(dataset,criterion):
      dataset = Likert(dataset, criterion)
      dataset = np.array(dataset, dtype='f')
      dataset = dataset/np.sqrt(np.sum(np.square(dataset),axis=0))

      return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral" ]]))
criterion = ['max','max','max','min','max','max']
Euclidean(dataset, criterion)

array([[0.46714184, 0.36618057, 0.5055601 , 0.5068533 , 0.48112524,
        0.6708204 ],
       [0.5839273 , 0.659125  , 0.45500413, 0.5990084 , 0.28867516,
        0.372678  ],
       [0.42042765, 0.48824075, 0.53083813, 0.41469812, 0.67357534,
        0.5217492 ],
       [0.51385605, 0.43941668, 0.5055601 , 0.4607757 , 0.48112524,
        0.372678  ]], dtype=float32)

In [ ]:
# روش نرمالیزه کردن فازی
def FuzzyNorm(dataset,criterion):
      dataset = Likert(dataset, criterion)
      dataset = np.array(dataset, dtype='f')

      for j in range(dataset.shape[1]):
          if criterion[j] == 'max':
              dataset[:,j] = (dataset[:,j] - np.min(dataset[:,j]))/(np.max(dataset[:,j]) - np.min(dataset[:,j]))

          else:
              dataset[:,j] = (np.max(dataset[:,j]) - dataset[:,j])/(np.max(dataset[:,j]) - np.min(dataset[:,j]))

      return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral" ]]))
criterion = ['max','max','max','min','max','max']
FuzzyNorm(dataset, criterion)

array([[0.28571433, 0.        , 0.6666667 , 0.5       , 0.5       ,
        1.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.41666666, 1.        , 1.        , 1.        ,
        0.5       ],
       [0.57142866, 0.25      , 0.6666667 , 0.75      , 0.5       ,
        0.        ]], dtype=float32)

#**Non-Compensatory**

In [ ]:
# روش تسلط

import itertools
import numpy as np

def Dominance(dataset, criterion):
      dataset = Likert(dataset, criterion)

      for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]

      for i in range (dataset.shape[0]):

          Dominance = np.greater_equal(dataset[i,:],dataset)

          for x in range(Dominance.shape[0]):
              if x!=i:
                if Dominance[x,:].all() == True:
                  print("Option", i+1 ,"is dominant over ", x+1)
                  dataset =np.delete(dataset,x,0)
      np.set_printoptions(suppress = True)
      return(dataset)


dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Very Much"   ]]))
criterion = ['max','max','max','min','max','max']
Dominance(dataset, criterion)


Option 4 is dominant over  1


array([[    2.5,  2700. , 18000. ,    -6.5,     3. ,     5. ],
       [    1.8,  2000. , 21000. ,    -4.5,     7. ,     7. ],
       [    2.2,  1800. , 20000. ,    -5. ,     5. ,     9. ]],
      dtype=float32)

In [ ]:
# روش حداکثر حداقل‌ها
def Maximin (dataset, criterion):
    dataset = NormMinMax(dataset,criterion)
    Rank = np.max(np.min(dataset, axis=1))

    for i in range(dataset.shape[0]):
      if np.min(dataset[i,:]) == Rank:
          print("Option" , i+1 ,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
criterion = ['max','max','max','min','max','max']
Maximin(dataset, criterion)

Option 3 is selected


In [ ]:
# روش حداکثر حداکثرها
def Maximax (dataset, criterion):

    dataset = NormMinMax(dataset,criterion)
    Rank = np.max(np.max(dataset, axis=1))

    for i in range(dataset.shape[0]):
      if np.max(dataset[i,:]) == Rank:
          print("Option" , i+1 ,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
criterion = ['max','max','max','min','max','max']
Maximax(dataset, criterion)

Option 1 is selected
Option 2 is selected
Option 3 is selected


In [ ]:
# روش هروکس
def Hurwicz(dataset , alpha , criterion):
    dataset = NormMinMax(dataset,criterion)
    H = alpha*np.min(dataset, axis=1) + (1-alpha)*np.max(dataset, axis=1)
    Rank = np.max(H)

    for i in range(H.shape[0]):
        if H[i] == Rank:
          print("Option",i+1,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
criterion = ['max','max','max','min','max','max']
Hurwicz(dataset , 0.05 , criterion)

Option 3 is selected


In [ ]:
# روش ارضای جامع
def Conjunctive(dataset , criterion, Threshold):
    dataset = Likert(dataset, criterion)

    for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]
            T[j] = - T[j]

    for i in range(dataset.shape[0]):
        if np.greater_equal(dataset[i,:], Threshold).all() == True:
          print("Option",i+1,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
T = np.array(([1.8 , 1500 , 15000 , 6 , 5 , 6]),dtype='f')
criterion = ['max','max','max','min','max','max']
Conjunctive(dataset , criterion , T)

Option 1 is selected
Option 3 is selected


In [ ]:
# روش ارضای تکی
def Disjunctive(dataset , criterion, Threshold):
    dataset = Likert(dataset, criterion)

    for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]
            T[j] = - T[j]

    for i in range(dataset.shape[0]):
        if np.greater_equal(dataset[i,:], Threshold).any() == True:
          print("Option",i+1,"is selected")

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.2 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Neutral"   ]]))
T = np.array(([2.3 ,  2000 , 22000 , 4.5 , 6 , 8]),dtype='f')
criterion = ['max','max','max','min','max','max']
Disjunctive(dataset , criterion , T)

Option 1 is selected
Option 2 is selected
Option 3 is selected


In [ ]:
# روش لغت نامه‌ای
def Lexicographic(dataset , criterion, Prio):
    dataset = Likert(dataset, criterion)
    data2 = np.copy(dataset)
    for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]

    for j in range(Prio.shape[0]):
        Best = np.max(dataset[:,Prio[j]-1])
        dataset = np.delete(dataset, np.where((dataset[:,Prio[j]-1] !=Best))[0], axis=0)
        if dataset.shape[0] == 1:
            for j in range (dataset.shape[1]):
                if criterion[j] == 'min':
                  dataset[:,j] = -dataset[:,j]
            print("Option",np.where((data2==dataset).all(-1))[0][0]+1, "is selected")
            return(dataset)




dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.2 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Very Much"   ]]))
Prio = np.array([1,3,2,4,5,6])
criterion = ['max','max','max','min','max','max']
Lexicographic(dataset , criterion , Prio)

Option 4 is selected


array([[2.2e+00, 1.8e+03, 2.0e+04, 5.0e+00, 5.0e+00, 9.0e+00]],
      dtype=float32)

In [ ]:
# روش نیمه لغت‌ نامه‌ای
def SemiLexicographic(dataset , criterion, Prio, Tolerance):
    dataset = Likert(dataset, criterion)
    data2 = np.copy(dataset)
    for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]

    for j in range(Prio.shape[0]):
        Best = np.max(dataset[:,Prio[j]-1])
        dataset = np.delete(dataset, np.where((dataset[:,Prio[j]-1] <Best*(1-Tolerance)))[0], axis=0)

        if dataset.shape[0] == 1:
            for j in range (dataset.shape[1]):
                if criterion[j] == 'min':
                  dataset[:,j] = -dataset[:,j]
            print("Option",np.where((data2==dataset).all(-1))[0][0]+1, "is selected")
            return(dataset)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  "Neutral"    , "Very Much" ],
                     [2.2 ,  2700 ,  18000 ,  6.5 ,  "Low"        , "Neutral"   ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  "Much"       , "Much"      ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  "Neutral"    , "Very Much"   ]]))
Prio = np.array([1,3,2,4,5,6])
Tolerance = 0.1
criterion = ['max','max','max','min','max','max']
SemiLexicographic(dataset , criterion , Prio, Tolerance)

Option 2 is selected


array([[2.2e+00, 2.7e+03, 1.8e+04, 6.5e+00, 3.0e+00, 5.0e+00]],
      dtype=float32)

In [ ]:
# روش جایگشت
def Permutation(dataset , criterion, weight):
      dataset = Likert(dataset, criterion)

      for j in range (dataset.shape[1]):
          if criterion[j] == 'min':
            dataset[:,j] = -dataset[:,j]

      # Computing pairwise weights
      H = np.empty((dataset.shape[0] , dataset.shape[0]))
      for i in range(dataset.shape[0]):
        for j in range(dataset.shape[0]):
          H[i,j] = np.sum(weight[np.where(np.greater_equal(dataset[i,:], dataset[j,:]))[0]])

      #Permutations of Options
      s = np.arange(weight.shape[0])
      comb = itertools.permutations(s, weight.shape[0])
      Per = np.array(list(comb))

      #Accordant Set
      #Dissenting Set

      Acc= np.empty((Per.shape[0], 1))
      Diss= np.empty((Per.shape[0], 1))

      for k in range(Per.shape[0]):
        s=0
        x=0
        for i in range(Per.shape[1]):
          for j in range(i+1, Per.shape[1]):
            a = Per[k,i]
            b = Per[k,j]
            s+= H[a,b]
            x+= H[b,a]
          Acc[k,:] = s
          Diss[k,:] = x

      Permutation = Acc - Diss
      print(Per[np.argmax(Permutation)])


dataset = np.array(([[2    ,  15  ,  20],
                     [2.2  ,  27  ,  18],
                     [1.8  ,  20  ,  20]]))
criterion = np.array(['max', 'min' , 'max'])
weight = np.array([0.2 , 0.5 , 0.3])

Permutation(dataset , criterion, weight)

[0 2 1]


#**Compensatory**

## Entropy

In [ ]:
# آنتروپی

def entropy_method(dataset, criterion):
    # Decision Matrix
    dataset = Normalization(dataset, criterion)
    ln_dataset = np.log(dataset)

    #Entropy
    E = np.zeros((dataset.shape))
    K = 1/np.log(dataset.shape[0])
    E = -K*np.sum(dataset*ln_dataset, axis=0)

    #d
    d = 1 - E

    #Weight
    w = d / (np.sum(d))

    print("Entropy:", E)
    print("Matrix d:", d)
    print("Weights:", w)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  5 , 9 ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  3 , 5 ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  7 , 7 ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  5 , 5 ]]))
criterion = ['max','max','max','min','max','max']
entropy_method(dataset, criterion)

Entropy: [0.9946889  0.9829482  0.99888754 0.99327105 0.97032267 0.97714126]
Matrix d: [0.00531107 0.01705182 0.00111246 0.00672895 0.02967733 0.02285874]
Weights: [0.06418961 0.20608823 0.0134452  0.08132605 0.3586802  0.2762707 ]


## SAW & WASPAS

In [ ]:
# مجموع وزنی ساده

def SAW(dataset, weights, criterion):
    dataset = NormMinMax(dataset, criterion)
    weighted = np.sum(dataset*weights, axis = 1)
    sorted = np.sort(weighted)
    print("Weighted:", weighted)
    for i in range (sorted.shape[0]):
      print("rank", i+1 ,"is option",np.where(weighted==sorted[-(i+1)])[0][0]+1)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  5 , 9 ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  3 , 5 ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  7 , 7 ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  5 , 5 ]]))
w = np.array([0.2,   0.1,   0.1,   0.1,  0.2,  0.3])
criterion = ['max','max','max','min','max','max']
SAW(dataset, w, criterion)

Weighted: [0.83546898 0.70732602 0.8514074  0.73742858]
rank 1 is option 3
rank 2 is option 1
rank 3 is option 4
rank 4 is option 2


In [ ]:
# روش وزنی ترکیبی

def WASPAS(dataset, weights, Lambda, criterion):
    dataset = NormMinMax(dataset, criterion)
    weighted_sum = np.sum(dataset*weights, axis = 1)
    weighted_product = np.prod(dataset**weights, axis = 1)
    was = Lambda*weighted_sum + (1-Lambda)*weighted_product
    sorted = np.sort(was)
    print("Weighted:", was)
    for i in range (sorted.shape[0]):
      print("rank", i+1 ,"is option",np.where(was==sorted[-(i+1)])[0][0]+1)

dataset = np.array(([[2   ,  1500 ,  20000 ,  5.5 ,  5 , 9 ],
                     [2.5 ,  2700 ,  18000 ,  6.5 ,  3 , 5 ],
                     [1.8 ,  2000 ,  21000 ,  4.5 ,  9 , 3 ],
                     [2.2 ,  1800 ,  20000 ,  5   ,  5 , 5 ]]))
w = np.array([0.2,   0.1,   0.1,   0.1,  0.2,  0.3])
criterion = ['max','max','max','min','max','max']
WASPAS(dataset, w, 0.8 ,criterion)

Weighted: [0.79937676 0.67837223 0.70517465 0.70194596]
rank 1 is option 1
rank 2 is option 3
rank 3 is option 4
rank 4 is option 2


## PCM

In [ ]:
# ماتریس مقایسات زوجی

def PCM(dataset, IIR, In_method, Weight_method):
      dataset = Likert_PCM(dataset)
      eigenvalues, eigenvectors = LA.eig(dataset)
      Lambda = np.max(abs(eigenvalues.real))
      II = (Lambda-dataset.shape[0])/(dataset.shape[0]-1)
      IR = II/(IIR[dataset.shape[0]-1])

      if IR>0.1:
          print("Inconsistent PCM")
          # روش لگاریتم کمترین مربعات
          if In_method == "LLSM":
              W = np.prod(dataset, axis=1)**(1/dataset.shape[0])/np.sum(np.prod(dataset, axis=1)**(1/dataset.shape[0]))
              print("Weights with LLSM method:", W)


          # روش مقدار ویژه
          if In_method == "EVM":
              b = np.zeros(dataset.shape[0])
              def f(w):
                  y = np.dot((dataset - Lambda*np.identity(dataset.shape[0])),w) - b
                  return np.dot(y,y)

              cons = ({'type': 'eq', 'fun': lambda w: w.sum() - 1})
              res = optimize.minimize(f, np.zeros(dataset.shape[0]), method='SLSQP', constraints=cons,
                                      options={'disp': False})
              W = res['x']
              print("Weights with EVM method:", W)


          # روش کمترین مربعات
          if In_method == "LSM":
              def f(w):
                  y =0
                  for i in range (dataset.shape[0]):
                      for j in range(dataset.shape[1]):
                          y += (dataset[i,j]*w[j]-w[i])**2
                  return y

              cons = ({'type': 'eq', 'fun': lambda w: w.sum() - 1})
              res = optimize.minimize(f, np.zeros(dataset.shape[0]), method='SLSQP', constraints=cons,
                                      options={'disp': False})
              W = res['x']
              print("Weights with LSM method:", W)


      else:
          # جمع سطری
          if Weight_method == "Row":
              dataset = np.sum(dataset, axis = 1)
              dataset = dataset/np.sum(dataset)
              print("Weights with summation of rows method:", dataset)
              return
          # جمع ستونی
          elif Weight_method == "Column":
              dataset = np.sum(dataset, axis = 0)
              dataset = 1/dataset
              dataset = dataset/np.sum(dataset)
              print("Weights summation of columns method:", dataset)
              return

          # میانگین حسابی
          elif Weight_method == "Arithmetic Mean":
              dataset = dataset/np.sum(dataset, axis =0)
              dataset = np.mean(dataset, axis=1)
              print("Weights with Arithmetic mean method:", dataset)
              return

          # میانگین هندسی
          elif Weight_method == "Geometric Mean":
              dataset = gmean(dataset, axis = 1)
              dataset = dataset/np.sum(dataset)
              print("Weights with Geometric mean method:", dataset)
              return

dataset = np.array(([[ 1   ,  5   ,  6   ,  7],
                     [1/5  ,  1   ,  4   ,  6],
                     [1/6  ,  1/4 ,  1   ,  4],
                     [1/7  ,  1/6 ,  1/4 ,  1]]))
IIR = np.array([0 , 0 , 0.58 ,  0.9, 1.12, 1.24, 1.32, 1.41, 1.45, 1.51])
Weight_method = "Row"
In_method = "EVM"
PCM(dataset, IIR, In_method, Weight_method)


Inconsistent PCM
Weights with EVM method: [0.61867427 0.23531693 0.10093078 0.04507801]


## BWM

In [ ]:
# روش بهترین-بدترین

def BWM(Best_to_Others, Others_to_Worst, BWM_method = "Linear"):
    bo = Likert_PCM(Best_to_Others)
    wo = Likert_PCM(Others_to_Worst)

    if BWM_method == "Linear":
          #تعریف محدودیت ها و تابع هدف کسری
          def target_functionLR(variables):
              Wbest      = variables[np.argmin(bo)]
              Wworst      = variables[np.argmin(wo)]
              cons_1  = []
              cons_2  = []

              for i in range(0, bo.shape[0]):
                  cons_1.append(abs(Wbest - bo[i]*variables[i]))
              cons_1.extend([-item for item in cons_1])

              for i in range(0, wo.shape[0]):
                  cons_2.append(abs(variables[i] - wo[i] * Wworst))
              cons_2.extend([-item for item in cons_2])

              cons = cons_1 + cons_2
              eps = np.max(cons)

              return eps

          # مقادیر اولیه متغیرها، حدود متغیرها و بهینه سازی
          np.random.seed(42)
          variables = np.random.uniform(low = 0.001, high = 1.0, size = bo.shape[0])
          variables = variables / np.sum(variables)
          bounds    = Bounds([0]*bo.shape[0], [1]*bo.shape[0])
          w_cons    = LinearConstraint(np.ones(bo.shape[0]), [1], [1])
          results   = minimize(target_functionLR, variables, method = 'trust-constr', bounds = bounds, constraints = [w_cons])
          weights   = results.x
          obj = target_functionLR(results.x)

          print("Epsilon is:", obj)
          for i in range (weights.shape[0]):
              print("Criteria",i+1,"'s weight is:", weights[i])

    if BWM_method == "Fractional":
          #تعریف محدودیت ها و تابع هدف کسری
          def target_functionFR(variables):
              Wbest      = variables[np.argmin(bo)]
              Wworst      = variables[np.argmin(wo)]
              cons_1  = []
              cons_2  = []
              penalty = 0
              for i in range(0, bo.shape[0]):
                  cons_1.append(abs(Wbest/variables[i] - bo[i]))
              cons_1.extend([-item for item in cons_1])
              for i in range(0, wo.shape[0]):
                  cons_2.append(abs(variables[i]/Wworst - wo[i]))
              cons_2.extend([-item for item in cons_2])
              cons = cons_1 + cons_2
              eps = np.max(cons)
              return eps

          # مقادیر اولیه متغیرها، حدود متغیرها و بهینه سازی
          np.random.seed(42)
          variables = np.random.uniform(low = 0.001, high = 1.0, size = bo.shape[0])
          variables = variables / np.sum(variables)
          bounds    = Bounds([0]*bo.shape[0], [1]*bo.shape[0])
          w_cons    = LinearConstraint(np.ones(bo.shape[0]), [1], [1])
          results   = minimize(target_functionFR, variables, method = 'trust-constr', bounds = bounds, constraints = [w_cons])
          weights   = results.x
          obj = target_functionFR(results.x)

          print("Epsilon is:", obj)
          for i in range (weights.shape[0]):
              print("Criteria",i+1,"'s weight is:", weights[i])

    #Input-based consistency ratio
    print("\nInput-based consistency ratio")
    CR = np.zeros(bo.shape[0])
    BW = np.max(bo)
    for j in range(bo.shape[0]):
        if BW ==1:
            CR[j] = 0
        else:
            CR[j] = np.abs(bo[j]*wo[j] - BW)/(BW**2 - BW)

    CR = np.max(CR)
    threshold = [0, 0, 0, 0.1667, 0.1898, 0.2306, 0.2643, 0.2819, 0.2958, 0.3062]

    if (CR <= threshold[int(BW)]):
        print("Consistency retio is:", CR, "which is acceptable")
    else:
       print("Consistency retio is:", CR, "which is inconsistent")

    #Output-based consistency ratio
    print("\nOutput-based consistency ratio")
    threshold = [0, 0.44, 1, 1.63, 2.3, 3, 3.73, 4.47, 5.23]
    CI = obj/threshold[int(BW)-1]
    if  CI<0.1:
        print("Consistency retio is:", CI, "which is acceptable")
    else:
        print("Consistency retio is:", CI, "which is inconsistent")

Best_to_Others =np.array([8,2,1])
Others_to_Worst =  np.array([1,5,8])
BWM(Best_to_Others , Others_to_Worst , "Fractional")

Epsilon is: 0.2583427434414858
Criteria 1 's weight is: 0.07142856947753136
Criteria 2 's weight is: 0.33868983013874787
Criteria 3 's weight is: 0.5898816003837208

Input-based consistency ratio
Consistency retio is: 0.03571428571428571 which is acceptable

Output-based consistency ratio
Consistency retio is: 0.057794797190488995 which is acceptable


## AHP

In [ ]:
!pip install ahpy
import numpy as np
import itertools
import ahpy

### Example 1

In [ ]:
import ahpy
K1_comparisons = {('D1', 'D2'): 1/3, ('D1', 'D3'): 3, ('D2', 'D3'): 5}
K2_comparisons = {('D1', 'D2'): 1, ('D1', 'D3'): 8, ('D2', 'D3'): 8}
K3_comparisons = {('D1', 'D2'): 5, ('D1', 'D3'): 8, ('D2', 'D3'): 5}
K4_comparisons = {('D1', 'D2'): 1, ('D1', 'D3'): 5, ('D2', 'D3'): 5}
K5_comparisons = {('D1', 'D2'): 5, ('D1', 'D3'): 9, ('D2', 'D3'): 4}
K6_comparisons = {('D1', 'D2'): 5, ('D1', 'D3'): 8, ('D2', 'D3'): 6}
K7_comparisons = {('D1', 'D2'): 7, ('D1', 'D3'): 5, ('D2', 'D3'): 1/6}
K8_comparisons = {('D1', 'D2'): 4, ('D1', 'D3'): 8, ('D2', 'D3'): 7}
K9_comparisons = {('D1', 'D2'): 6, ('D1', 'D3'): 7, ('D2', 'D3'): 5}
K10_comparisons = {('D1', 'D2'):1/3, ('D1', 'D3'): 7, ('D2', 'D3'): 8}

criteria_comparisons = {('K1', 'K2'): 3, ('K1', 'K3'): 5, ('K1', 'K4'): 5, ('K1', 'K5'): 7, ('K1', 'K6'): 8, ('K1', 'K7'): 8, ('K1', 'K8'): 6, ('K1', 'K9'): 5, ('K1', 'K10'): 5,
                        ('K2', 'K3'): 5, ('K2', 'K4'): 5, ('K2', 'K5'): 7, ('K2', 'K6'): 8, ('K2', 'K7'): 8, ('K2', 'K8'): 6, ('K2', 'K9'): 5, ('K2', 'K10'): 5,
												('K3', 'K4'): 1/3, ('K3', 'K5'): 5, ('K3', 'K6'): 6, ('K3', 'K7'): 7, ('K3', 'K8'): 5, ('K3', 'K9'): 3, ('K3', 'K10'): 4,
												('K4', 'K5'): 4, ('K4', 'K6'): 3, ('K4', 'K7'): 7, ('K4', 'K8'): 5, ('K4', 'K9'): 1, ('K4', 'K10'): 5,
												('K5', 'K6'): 4, ('K5', 'K7'): 1/5, ('K5', 'K8'): 1/7, ('K5', 'K9'): 1/3, ('K5', 'K10'): 3,
												('K6', 'K7'): 5, ('K6', 'K8'): 1/5, ('K6', 'K9'): 1/3, ('K6', 'K10'): 3,
												('K7', 'K8'): 1/3, ('K7', 'K9'): 1/3, ('K7', 'K10'): 3,
												('K8', 'K9'): 1, ('K8', 'K10'): 3,
												('K9', 'K10'): 3}

K1 = ahpy.Compare('K1', K1_comparisons, precision=4, random_index='saaty')
K2 = ahpy.Compare('K2', K2_comparisons, precision=4, random_index='saaty')
K3 = ahpy.Compare('K3', K3_comparisons, precision=4, random_index='saaty')
K4 = ahpy.Compare('K4', K4_comparisons, precision=4, random_index='saaty')
K5 = ahpy.Compare('K5', K5_comparisons, precision=4, random_index='saaty')
K6 = ahpy.Compare('K6', K6_comparisons, precision=4, random_index='saaty')
K7 = ahpy.Compare('K7', K7_comparisons, precision=4, random_index='saaty')
K8 = ahpy.Compare('K8', K8_comparisons, precision=4, random_index='saaty')
K9 = ahpy.Compare('K9', K9_comparisons, precision=4, random_index='saaty')
K10 = ahpy.Compare('K10', K10_comparisons, precision=4, random_index='saaty')
criteria = ahpy.Compare('Criteria', criteria_comparisons, precision=4, random_index='saaty')

In [ ]:
criteria.add_children([K1, K2, K3, K4, K5, K6, K7, K8, K9, K10])
print("وزن نهایی گزینه ها: ", criteria.target_weights)
print("وزن هر گزینه در معیار اول: ",K1.local_weights)
print("وزن هر گزینه در معیار دوم: ",K2.local_weights)
print("وزن هر گزینه در معیار سوم: ",K3.local_weights)
print("وزن هر گزینه در معیار چهارم: ",K4.local_weights)
print("وزن هر گزینه در معیار پنجم: ",K5.local_weights)
print("وزن هر گزینه در معیار ششم: ",K6.local_weights)
print("وزن هر گزینه در معیار هفتم: ",K7.local_weights)
print("وزن هر گزینه در معیار هشتم: ",K8.local_weights)
print("وزن هر گزینه در معیار نهم: ",K9.local_weights)
print("وزن هر گزینه در معیار دهم: ",K10.local_weights)

In [ ]:
print("گزارش نهایی و کلی")
report = criteria.report(show=True)

### Example 2

In [ ]:
cars = ('civic', 'saturn', 'escort', 'clio')

gas_m = dict(zip(cars, (34, 27, 24, 28)))
gas = ahpy.Compare('gas', gas_m, precision=3)

rel_m = dict(zip(itertools.combinations(cars, 2), (2, 5, 1, 3, 2, 0.25)))
rel = ahpy.Compare('rel', rel_m, 3)

style_m = {('civic', 'escort'): 4,
            ('saturn', 'civic'): 4, ('saturn', 'escort'): 4, ('saturn', 'clio'): 0.25,
            ('clio', 'civic'): 6, ('clio', 'escort'): 5}
style = ahpy.Compare('style', style_m, precision=3)

cri_m = {('style', 'rel'): 0.5, ('style', 'gas'): 3,
          ('rel', 'gas'): 4}
goal = ahpy.Compare('goal', cri_m)

goal.add_children([gas, rel, style])
print("وزن نهایی گزینه ها: ", goal.target_weights)

### Example 3

In [ ]:
a_m = {('b', 'c'): 1}
b_m = {('d', 'e'): 4}
c_m = {('f', 'g'): 1, ('g', 'h'): 1/2}
d_m = {('i', 'j'): 2}
e_m = {'x': 1, 'y': 2, 'z': 3}
f_m = {('k', 'l'): 1/9}
g_m = {'x': 1, 'y': 3, 'z': 6}
h_m = {'x': 2, 'y': 4, 'z': 4}
i_m = {'x': 2, 'y': 4, 'z': 4}
j_m = {'x': 1, 'y': 2, 'z': 3}
k_m = {'x': 2, 'y': 4, 'z': 4}
l_m = {('m', 'n'): 1}
m_m = {'x': 1, 'y': 2, 'z': 3}
n_m = {'x': 1, 'y': 3, 'z': 6}

a = ahpy.Compare('a', a_m, precision=4)
b = ahpy.Compare('b', b_m, precision=4)
c = ahpy.Compare('c', c_m, precision=4)
d = ahpy.Compare('d', d_m, precision=4)
e = ahpy.Compare('e', e_m, precision=4)
f = ahpy.Compare('f', f_m, precision=4)
g = ahpy.Compare('g', g_m, precision=4)
h = ahpy.Compare('h', h_m, precision=4)
i = ahpy.Compare('i', i_m, precision=4)
j = ahpy.Compare('j', j_m, precision=4)
k = ahpy.Compare('k', k_m, precision=4)
l = ahpy.Compare('l', l_m, precision=4)
m = ahpy.Compare('m', m_m, precision=4)
n = ahpy.Compare('n', n_m, precision=4)

l.add_children([m, n])
d.add_children([i, j])
f.add_children([l, k])
b.add_children([d, e])
c.add_children([h, f, g])
a.add_children([b, c])

nodes = [(a, [b, c]), (b, [d, e]), (c, [f, g, h]), (d, [i, j]), (f, [k, l]), (l, [m, n])]
permutations = itertools.permutations(nodes)
for permutation in permutations:
     for node in permutation:
         node[0].add_children(node[1])

h.report()

# **BOLD TEXT**